platform :ios, '7.0'
pod 'AFNetworking','~> 2.0'
pod 'MJExtension'
pod 'MJRefresh'
pod 'SVProgressHUD'
pod 'FontAwesomeKit', '~> 2.2.0'
pod 'KNSemiModalViewController_hons82', '~> 0.4.4'
pod 'PNChart'

